// src/app/layout.tsx

import type { Metadata } from "next";
// Reverting to the custom fonts defined previously, as your CSS relies on them
import { Playfair_Display, Inter } from "next/font/google"; 
import "./globals.css";
import Header from '../components/Header'; // You need to import this here
import Footer from '../components/Footer'; // You need to import this here


// Re-defining the fonts and variables used by your Tailwind config
const headingFont = Playfair_Display({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const bodyFont = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 💥 FIX: All base classes are applied here to bypass the PostCSS error.
        className={`
          bg-neutralGray 
          ${headingFont.variable} ${bodyFont.variable} 
          font-body antialiased
        `}
      >
        {/* 💥 FIX: Re-adding Header to the layout */}
        <Header />
        
        {/* 💥 FIX: Adding the max-width content wrapper */}
        <div className="">
            {children}
        </div>

        {/* 💥 FIX: Re-adding Footer to the layout */}
        <Footer />
      </body>
    </html>
  );
}